export const metadata = {
  title: "Rasayan Authentication",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-full h-full grid place-items-center">{children}</div>
  );
}
